# Generated by Django 3.2.3 on 2022-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('dificallity', models.CharField(choices=[('e', 'easy'), ('m', 'medium'), ('d', 'dificial')], max_length=1)),
                ('is_rude', models.BooleanField(default=False)),
                ('is_proved', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('d', 'dare'), ('t', 'truth')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
